### ISSUE TITLE
Class 05 Peer Review

### ISSUE THREAD

**Issue by erinroby** [dmcfly85/portfolio#5]
We talked a lot cleaning up the white space and making everything consistent. Also, turning the nav array into an object constructor in nav.js, combining nav.js and tabView.js into one file, and refactoring the tabView.js logic a bit, notes shared as we went.

**Comment by dmcfly85** [comment]
Thanks for the great feedback. I did lots of cleanup last weekend.

**Comment by dmcfly85** [comment]
Thanks for the great feedback. I did lots of cleanup last weekend.
